name: Tinybird - CI Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  ci_branching:
    uses: tinybirdco/ci/.github/workflows/ci_branching.yml@v1.0.2
    secrets: 
      admin_token: ${{ secrets.ADMIN_TOKEN }}
      tb_host: ${{ secrets.TB_HOST }}